FROM ubuntu:18.04

RUN apt-get update
RUN apt-get install -y build-essential git curl

RUN apt-get install -y python3.9 python3.9-distutils
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
RUN python3.9 get-pip.py
RUN rm get-pip.py
RUN python3.9 -m pip install pip

ADD . /home/app
WORKDIR /home/app
RUN python3.9 -m pip3 install -r requirements.txt

ENTRYPOINT ["python3.9", "-u", "run_algorithm.py"]
